"""add telegram_id to debtors

Revision ID: 6a655318bd87
Revises: 080ebbbdbe8f
Create Date: 2025-11-27 04:30:52.250494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a655318bd87'
down_revision: Union[str, Sequence[str], None] = '080ebbbdbe8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debtors', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_debtors_telegram_id'), 'debtors', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debtors_telegram_id'), table_name='debtors')
    op.drop_column('debtors', 'telegram_id')
    # ### end Alembic commands ###
